# Generated by Django 2.2 on 2020-01-03 16:32

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hsm.POMaker
import hsm.pomodels
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_job_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_job_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('state', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], default='UNPAID', max_length=10)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('bill_date', models.DateField(auto_now_add=True, null=True)),
                ('sub_total', models.FloatField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_maintenance_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
        migrations.CreateModel(
            name='PartnerVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('vehicle', models.CharField(choices=[('Four Wheeler', 'Four Wheeler'), ('Two Wheeler', 'Two Wheeler'), ('Other', 'Other')], max_length=20, null=True)),
                ('registration_number', models.CharField(max_length=40, null=True, unique=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_partnervehicle_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_vehicle_rel',
            },
        ),
        migrations.CreateModel(
            name='ResCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('code', models.CharField(max_length=40, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_rescountry_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_rescountry_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'res_countries',
            },
        ),
        migrations.CreateModel(
            name='ResPartner',
            fields=[
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, null=True)),
                ('street1', models.CharField(max_length=40, null=True)),
                ('street2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(max_length=40, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('mobile_no', models.CharField(max_length=15, null=True)),
                ('alt_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResCountry')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_respartner_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'res_partners',
            },
        ),
        migrations.CreateModel(
            name='ResProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_resproductcategory_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_resproductcategory_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Category',
                'db_table': 'res_product_category',
            },
        ),
        migrations.CreateModel(
            name='ResSociety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('registration_number', models.CharField(max_length=40, null=True, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('maintenance_due_days', models.PositiveIntegerField(default=0)),
                ('maintenance_due_charge', models.FloatField(default=0)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_ressociety_related', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_user', to='hsm.ResPartner')),
            ],
            options={
                'verbose_name_plural': 'Societies',
                'db_table': 'res_societies',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_service_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_service_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_vehicleparking_related', to=settings.AUTH_USER_MODEL)),
                ('parked_vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.PartnerVehicle')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResSociety')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_vehicleparking_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle_parking',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('number', models.CharField(editable=False, max_length=30, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Public Identifier')),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_transaction_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_transaction_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.CreateModel(
            name='SocietyServiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('price', models.IntegerField(null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_societyserviceline_related', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.Service')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.ResSociety')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_societyserviceline_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'society_service_lines',
            },
        ),
        migrations.CreateModel(
            name='SocietyEmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('society_name', models.CharField(max_length=50, null=True)),
                ('emp_photo', models.ImageField(null=True, upload_to='images')),
                ('emp_name', models.CharField(max_length=50, null=True)),
                ('emp_address', models.TextField(max_length=100, null=True)),
                ('emp_contact_no', models.CharField(max_length=10, null=True)),
                ('emp_aadhar_card_no', models.CharField(max_length=12, null=True)),
                ('emp_aadhar_card_photo', models.ImageField(null=True, upload_to='images')),
                ('emp_pan_card_no', models.CharField(max_length=10, null=True)),
                ('emp_pan_card_photo', models.ImageField(null=True, upload_to='images')),
                ('emp_joining_date', models.DateTimeField(null=True)),
                ('emp_working_hours', models.TimeField(null=True)),
                ('emp_salary', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_societyemployeedetail_related', to=settings.AUTH_USER_MODEL)),
                ('emp_job_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.Job')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_societyemployeedetail_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResWing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_reswing_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_reswing_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wing',
                'verbose_name_plural': 'Wings',
                'db_table': 'res_wings',
                'ordering': ['pk', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('code', models.CharField(max_length=40, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResCountry')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_resstate_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_resstate_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'res_states',
            },
        ),
        migrations.AddField(
            model_name='ressociety',
            name='society_wing_rel',
            field=models.ManyToManyField(db_table='society_wing_rel', to='hsm.ResWing'),
        ),
        migrations.AddField(
            model_name='ressociety',
            name='write_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_ressociety_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('product_no', models.CharField(default=hsm.pomodels.random_string, max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(choices=[('Stockable', 'Stockable'), ('Consumable', 'Consumable'), ('Services', 'Services')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.ResProductCategory')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_resproductdetail_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_resproductdetail_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Detail',
                'db_table': 'res_product_detail',
            },
        ),
        migrations.CreateModel(
            name='ResPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('period_type', models.CharField(blank=True, max_length=10, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_respost_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_respost_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'res_posts',
            },
        ),
        migrations.CreateModel(
            name='ResPartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_respartnertype_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_respartnertype_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'res_partner_type',
            },
        ),
        migrations.AddField(
            model_name='respartner',
            name='partner_post_rel',
            field=models.ManyToManyField(blank=True, db_table='partner_post_rel', to='hsm.ResPost', verbose_name='Partner post(s)'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='partner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResPartnerType'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='society',
            field=models.ManyToManyField(blank=True, db_table='partner_society_rel', to='hsm.ResSociety', verbose_name='Society(s)'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResState'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respartner',
            name='write_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_respartner_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResFlat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('number', models.IntegerField(null=True)),
                ('area', models.IntegerField(null=True)),
                ('registration_number', models.CharField(max_length=40, null=True, unique=True)),
                ('registration_date', models.DateTimeField(max_length=40, null=True)),
                ('is_allocated', models.BooleanField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_resflat_related', to=settings.AUTH_USER_MODEL)),
                ('flat_owner', models.ManyToManyField(blank=True, db_table='owner_flat_rel', related_name='owner_flat', to='hsm.ResPartner', verbose_name='Owner(s)')),
                ('flat_renter', models.ManyToManyField(blank=True, db_table='renter_flat_rel', related_name='renter_flat', to='hsm.ResPartner', verbose_name='Renter(s)')),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResSociety')),
                ('wing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResWing')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_resflat_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
                'db_table': 'res_flats',
                'ordering': ['number', 'wing', 'society'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('purchase_order_no', models.CharField(default=hsm.POMaker.random_string, max_length=50, null=True)),
                ('special_instructions', models.TextField(blank=True, max_length=50, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_purchaseordermaker_related', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.ResSociety')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_purchaseordermaker_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Purchase Order',
                'db_table': 'res_purchase_order_maker',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('product_unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_purchaseorderline_related', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.ResProductDetail')),
                ('purchase_order_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.PurchaseOrderMaker')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_purchaseorderline_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_order_line',
            },
        ),
        migrations.AddField(
            model_name='partnervehicle',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResPartner'),
        ),
        migrations.AddField(
            model_name='partnervehicle',
            name='society',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResSociety'),
        ),
        migrations.AddField(
            model_name='partnervehicle',
            name='write_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_partnervehicle_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('balance', models.FloatField(default=0.0, verbose_name='Current balance')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_partneraccount_related', to=settings.AUTH_USER_MODEL)),
                ('partner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.ResPartner')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_partneraccount_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partner_account',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_notice_related', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ResSociety')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_notice_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('cost', models.FloatField(default=0.0)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_maintenanceline_related', to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.Maintenance')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.Service')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_maintenanceline_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_lines',
            },
        ),
        migrations.AddField(
            model_name='maintenance',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.ResFlat'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hsm.Transaction'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='write_user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_maintenance_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_complaintcategory_related', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_complaintcategory_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint Category',
                'verbose_name_plural': 'Complaint Categories',
                'db_table': 'complaint_category',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('comment', models.TextField(null=True)),
                ('status_type', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], max_length=20, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('complaint_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsm.ComplaintCategory')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_complaint_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaint', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_complaint_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='AccountLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('write_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('amount', models.FloatField()),
                ('action_type', models.CharField(choices=[('CREDITED', 'CREDITED'), ('DEBITED', 'DEBITED')], max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hsm.PartnerAccount')),
                ('create_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_hsm_accountline_related', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hsm.Transaction')),
                ('write_user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_by_hsm_accountline_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_lines',
            },
        ),
        migrations.CreateModel(
            name='FlatMaintenanceView',
            fields=[
            ],
            options={
                'verbose_name': 'Flat Maintenance Dashboard',
                'verbose_name_plural': 'Flat Maintenance Dashboard',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hsm.maintenance',),
        ),
        migrations.CreateModel(
            name='ResVendorDetail',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Vendor Detail',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hsm.respartner',),
        ),
        migrations.AddField(
            model_name='purchaseordermaker',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsm.ResVendorDetail'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['bill_date'], name='maintenance_bill_da_d4b319_brin'),
        ),
    ]
