language: python
sudo: false
env:
  - TOX_ENV=py27-flake8
  - TOX_ENV=py36-flake8
  - TOX_ENV=py27-dj18
  - TOX_ENV=py27-dj19
  - TOX_ENV=py27-dj110
  - TOX_ENV=py27-dj111
  - TOX_ENV=py36-dj18
  - TOX_ENV=py36-dj19
  - TOX_ENV=py36-dj110
  - TOX_ENV=py36-dj111
  - TOX_ENV=py36-dj20
  - TOX_ENV=py36-dj21
before_install:
  - pyenv global system 3.6
install:
  - pip install -r requirements-test.txt
script:
  - tox -e $TOX_ENV
